config/routes.rb
Rails.application.routes.draw do
	root 'jobs#index'

	resources :jobs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
	validates :title, presence: { message: "cannot be blank." }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	def index
		@jobs = Job.all
	end

	def show
		@job = Job.find(params[:id])
	end

	def new
		@job = Job.new
	end

	def create
		@job = Job.create(job_params)
		if @job.save
			redirect_to jobs_path
		else
			render :new
		end
	end

	def edit
		@job = Job.find(params[:id])
	end

	def update
		@job = Job.find(params[:id])
		@job.update_attributes(job_params)
		if @job.update(job_params)
			redirect_to jobs_path
		else
			render :edit
		end
	end

	def destroy
		@job = Job.find(params[:id])
		@job.destroy
		redirect_to jobs_path
	end


	private

	def job_params
		params.require(:job).permit(:title, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
  <div>
    <span class="required-label">*</span>
    <%= f.label :title %>
    <br/><%= f.text_field :title %>
    <% if @job.errors[:title].any? %>
        <span class="field-error-message">&nbsp;required</span>
    <% end %>
  </div>
  <div>
    <%= f.label :description %><br/>
    <%= f.text_area :description, size: '60x6' %>
  </div>
  <div>
    <%= f.submit %>
    <button><%= link_to "Back", jobs_path %></button>
  </div>

<% end %>

<% if @job.errors.any? %>
    <div class="error_explanation">
      <%= pluralize(@job.errors.count, "error") %> kept this article from being saved:      
      <ul> 
        <% @job.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Posting</h1>

<%= render "form" %>

app/views/jobs/index.html.erb
<h1>RailsBridgeCorp Open Jobs</h1>

<% @jobs.each do |job| %>
	<section class="single-job">
		<h3><%= link_to job.title, job_path(job) %></h3>
		<p><%= job.description %></p>
		<h5><%= link_to "Edit Posting", edit_job_path(job) %></h5>
		<h5><%= link_to 'Delete Posting', job, method: :delete, data: { confirm: 'Are you sure?' } %></h5>
		<hr />
	</section>
<% end %>

app/views/jobs/new.html.erb
<h1>Add a Job</h1>

<%= render "form" %>

app/views/jobs/show.html.erb
<section class="show">
<h1><%= @job.title %></h1>
<p><%= @job.description %></p>
<h5><%= link_to "Edit", edit_job_path(@job) %></h5>
<h5><%= link_to 'Delete', @job, method: :delete, data: { confirm: 'Are you sure?' } %></h5>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header class='clearfix'>
      <div class="left-nav">
        <ul>
          <li><%= link_to "Home", jobs_path %></li>
        </ul>
      </div>
      <div class="right-nav">
        <ul>
          <li><%= link_to "Add Job", new_job_path %></li>
        </ul>
      </div>
    </header>
    <div class='content'>
      <%= yield %>
    </div>
  </body>
</html>